### ISSUE TITLE
Pin mapping to stm32f303

### ISSUE THREAD

**Issue by tekjar** [JoshMcguigan/betafpv-f3#3]
Hi,
Is there any doc to see how the board pins are connected to stm32f303? I'm trying similar stuff for spracing f3 board and want to find out pin mapping

**Comment by JoshMcguigan** [comment]
For the betafpv-f3, the easiest way for now is to check out the source code of [this library](https://github.com/JoshMcguigan/betafpv-f3/blob/master/src/lib.rs). If you are looking for the pinouts for the spracing f3, or any other board, I'd start with the [betaflight drivers for that board](https://github.com/betaflight/betaflight/tree/master/src/main/target/SPRACINGF3).

**Comment by tekjar** [comment]
Awesome. Thanks :)
